using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using System;

/// <summary>
/// MapGenerator.cs
/// June 25, 2021
/// Completed by Taylor Dauphinee
/// A script that creates a cave map using cellular automata
/// Followed from Sebastian Lague's Procedural Cave Generation
/// </summary>

public class MapGenerator : MonoBehaviour
{
    public int width;
    public int height;

    // Seeds allow the same random map to be generated by inputting the same seed
    public string seed;
    public bool useRandomSeed;

    [Range(0, 100)]
    public int randomFillPercent;

    int[,] map;

    private void Start()
    {
        GenerateMap();
    }

    private void Update()
    {
        if (Input.GetMouseButtonDown(0))
        {
            GenerateMap();
        }
    }

    void GenerateMap()
    {
        map = new int[width, height];

        RandomFillMap();

        for (int i = 0; i < 5; i++) // The value '5' can be changed and played around with same as the inspector values
        {
            SmoothMap();
        }

        MeshGenerator meshGen = GetComponent<MeshGenerator>();
        meshGen.GenerateMesh(map, 1); // 1 is a default value
    }

    void RandomFillMap()
    {
        if (useRandomSeed)
        {
            seed = Time.time.ToString();
        }

        System.Random pseudoRandom = new System.Random(seed.GetHashCode()); // GetHashCode allows a string to be converted to an integer

        for (int x = 0; x < width; x++)
        {
            for (int y = 0; y < height; y++)
            {
                if (x == 0 || x == width - 1 || y == 0 || y == height - 1) // We always want edge blocks to be walls
                {
                    map[x, y] = 1;
                }
                else // otherwise, it's random based on our fill percent and our seed
                {
                    map[x, y] = (pseudoRandom.Next(0, 100) < randomFillPercent) ? 1 : 0;
                }
            }
        }
    }

    // checks through the map and changes the grid values based on their neighbours
    void SmoothMap()
    {
        for (int x = 0; x < width; x++)
        {
            for (int y = 0; y < height; y++)
            {
                int neighbourWallTiles = GetSurroundingWallCount(x, y);

                if (neighbourWallTiles > 4)
                {
                    map[x, y] = 1;
                }
                else if (neighbourWallTiles < 4)
                {
                    map[x, y] = 0;
                }
            }
        }
    } // NOTE: could change rules per iteration

    int GetSurroundingWallCount(int gridX, int gridY)
    {
        int wallCount = 0;

        for (int neighbourX = gridX - 1; neighbourX <= gridX + 1; neighbourX++)
        {
            for (int neighbourY = gridY - 1; neighbourY <= gridY + 1; neighbourY++)
            {
                if (neighbourX >= 0 && neighbourX < width && neighbourY >= 0 && neighbourY < height)
                {
                    if (neighbourX != gridX || neighbourY != gridY)
                    {
                        wallCount += map[neighbourX, neighbourY];
                    }
                }
                else
                {
                    wallCount++;
                }
            }
        }

        return wallCount;
    }

    //// Debug method to visualize our map for now
    //private void OnDrawGizmos()
    //{
    //    if (map != null)
    //    {
    //        for (int x = 0; x < width; x++)
    //        {
    //            for (int y = 0; y < height; y++)
    //            {
    //                Gizmos.color = (map[x, y] == 1) ? Color.black : Color.white;
    //                Vector3 position = new Vector3(-width / 2 + x + 0.5f, 0f, -height / 2 + y + 0.5f);
    //                Gizmos.DrawCube(position, Vector3.one);
    //            }
    //        }
    //    }
    //}
}
